config/routes.rb
Rails.application.routes.draw do
  resources :messages, only: [:index, :create, :edit, :update, :destroy, :show]
  resources :rooms
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  root "rooms#index"

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :room
end

app/models/room.rb
class Room < ApplicationRecord
    has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: %i[ show edit update destroy ]

  # GET /messages or /messages.json
  # GET /messages or /messages.json
  def index
    if params[:room_id]
      @room = Room.find(params[:room_id])
      @messages = @room.messages
    else
      @messages = []
    end
  end


  # GET /messages/1 or /messages/1.json
  def show
    @message = Message.find(params[:id])
  end
  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
    respond_to do |format|
      format.turbo_stream
      format.html
    end
  end
  
  

  # POST /messages or /messages.json
  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        @message.broadcast_append_to @message.room, partial: @message, 
          locals: { message: @message }, target: "message-list"
        format.html { redirect_to @message, notice: "Message was successfully created." }
        format.json { render :show, status: :created, location: @message }
        format.turbo_stream
        
      else
        format.turbo_stream { render turbo_stream: turbo_stream.replace(@message, partial: "message", locals: { message: @message }) }
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1 or /messages/1.json
  def update
    @message = Message.find(params[:id])
  
    respond_to do |format|
      if @message.update(message_params)
        format.turbo_stream { render turbo_stream: turbo_stream.replace(@message) }
        format.html { redirect_to @message, notice: "Message was successfully updated." }
        format.json { render :show, status: :ok, location: @message }
        format.turbo_stream
      else
        format.turbo_stream { render :edit, status: :unprocessable_entity }
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end
  

  # DELETE /messages/1 or /messages/1.json
  def destroy
    @message.destroy!

    respond_to do |format|
      @message.broadcast_remove_to @message.room, target: @message
      format.html { redirect_to messages_path, status: :see_other, notice: "Message was successfully destroyed." }
      format.json { head :no_content }
      format.turbo_stream
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def message_params
      params.expect(message: [ :content, :room_id ])
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: %i[ show edit update destroy ]

  def index
    @rooms = Room.all
  
    @room = @rooms[0] unless @rooms.empty?
    @messages = []
    @messages = @room.messages unless @rooms.empty?
  end
  

  def show
  end

  def new
    @room = Room.new
  end

  def edit
  end

  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: "Room was successfully created." }
        format.json { render :show, status: :created, location: @room }
        format.turbo_stream
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: "Room was successfully updated." }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @room.destroy!

    respond_to do |format|
      format.html { redirect_to rooms_path, status: :see_other, notice: "Room was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

    def set_room
      @room = Room.find(params[:id])  
    end

    def room_params
      params.require(:room).permit(:name)  
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Chat Application" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_form.html.erb
<%= turbo_frame_tag "create-message-form-#{message.room&.id || 'new'}" do %>
  <%= form_with(model: message, id: 'message-form') do |form| %>
    <%= form.text_field :content %>
    <%= form.hidden_field :room_id, value: message.room&.id %>


    <div>
      <%= form.submit %>
    </div>
  <% end %>
<% end %>

app/views/messages/_message.html.erb
<%= turbo_frame_tag dom_id(message), class: "bg-white p-4 rounded shadow mb-2 flex justify-between items-center" do %>
  <div class="text-gray-800">
    <%= message.content %>
    <%= link_to 'Edit', edit_message_path(message), 
        data: { turbo_frame: dom_id(message) }, 
        class: "text-blue-600 hover:underline" %>
  </div>
  <div class="space-x-2">
    <%= button_to 'Delete', message_path(message), method: :delete,
        class: "text-red-600 hover:underline", form: { class: "inline" } %>
  </div>
<% end %>

app/views/messages/create.turbo_stream.erb
<%= turbo_stream.append "message-list", partial: "message", object: @message %>
<%= turbo_stream.replace "message-form", partial: "form", locals: {message: Message.new(content: "",room:@message.room)} %>

app/views/messages/destroy.turbo_stream.erb
<%= turbo_stream.remove @message %>

app/views/messages/edit.html.erb
<%= turbo_frame_tag dom_id(@message) do %>
  <%= form_with(model: @message, data: { turbo_frame: dom_id(@message) }) do |f| %>
    <div class="mb-2">
      <%= f.text_field :content, class: "border p-2 w-full", autofocus: true %>
    </div>
    <div>
      <%= f.submit "Update", class: "bg-blue-600 text-white px-4 py-2 rounded" %>
    </div>
  <% end %>
<% end %>

app/views/messages/edit.turbo_stream.erb
<%= turbo_stream.replace @message do %>
    <%= render partial: "form", locals: { message: @message } %>
  <% end %>
  

app/views/messages/index.html.erb
<div id='messages'>
  <%= turbo_frame_tag 'room-messages' do %>
    <div id='message-list'>
        <% @messages.each do |message| %>
          <%= render message %>
        <% end %>
    </div>
      <%= render partial: 'messages/form', locals: {message: Message.new(room: @room)} %>
    <%= turbo_stream_from @room %>
  <% end %>

</div>

app/views/messages/new.html.erb
<% content_for :title, "New message" %>

<h1>New message</h1>

<%= render "form", message: @message %>

<br>

<div>
  <%= link_to "Back to messages", messages_path %>
</div>

app/views/messages/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @message %>

<div>
  <%= link_to "Edit this message", edit_message_path(@message) %> |
  <%= link_to "Back to messages", messages_path %>

  <%= button_to "Destroy this message", @message, method: :delete %>
</div>

app/views/rooms/_form.html.erb
<div id='actions'>
  <%= form_with(model: room) do |form| %>
    <div>
      <%= form.label :name, style: "display: block" %>
      <%= form.text_field :name %>
    </div>

    <div>
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/rooms/_room.html.erb
<%= link_to messages_path(room_id: room.id), 
            data: { turbo_frame: 'room-messages' } do %>
  <div class='room'>
    <%= room.name %>
  </div>
<% end %>

app/views/rooms/create.turbo_stream.erb
<%= turbo_stream.append "room-list", partial: "room", object: @room %>
<%= turbo_stream.replace "actions", partial: "form", locals: {room: Room.new(name: "Room #{Room.count + 1}")} %>

app/views/rooms/edit.html.erb
<% content_for :title, "Editing room" %>

<h1>Editing room</h1>

<%= render "form", room: @room %>

<br>

<div>
  <%= link_to "Show this room", @room %> |
  <%= link_to "Back to rooms", rooms_path %>
</div>

app/views/rooms/index.html.erb
<div id='chatapp'>
  <div id='rooms'>
    <div id='room-list'>
      <% @rooms.each do |room| %>
        <%= render room %>
      <% end %>
    </div>
    <%= render partial: 'form', locals: { room: Room.new(name: "Room #{Room.count + 1}") } %>
  </div>

  <div id='messages'>
    <%= turbo_frame_tag 'room-messages' do %>
      <div id='message-list'>
        <% @messages.each do |message| %>
          <%= render message %>
        <% end %>
      </div>
      <%= render partial: 'messages/form', locals: { message: Message.new(room: @room) } %>

      <%= turbo_stream_from @room %>
    <% end %>


  </div> 
</div>

app/views/rooms/new.html.erb
<% content_for :title, "New room" %>

<h1>New room</h1>

<%= render "form", room: @room %>

<br>

<div>
  <%= link_to "Back to rooms", rooms_path %>
</div>

app/views/rooms/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @room %>

<div>
  <%= link_to "Edit this room", edit_room_path(@room) %> |
  <%= link_to "Back to rooms", rooms_path %>

  <%= button_to "Destroy this room", @room, method: :delete %>
</div>